---
- name: Update On Primary
  hosts: AnnaMacbook

  tasks:
  - name: Set SP Secret
    ansible.builtin.shell: |
      # These should here. But I want which to fail if absent
      which jq
      which az

      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

      export AZURE_CERT_MANAGER_SP_APP_ID=`az keyvault secret show --vault-name idjhomelabakv --name azure-payg-dnssp-client-id -o json | jq -r .value | tr -d '\n'`
      export AZURE_CERT_MANAGER_SP_PASSWORD=`az keyvault secret show --vault-name idjhomelabakv --name azure-payg-dnssp-client-pass -o json | jq -r .value | tr -d '\n'`
      export AZURE_SUBSCRIPTION_ID=`az keyvault secret show --vault-name idjhomelabakv --name azure-payg-dnssp-client-subid -o json | jq -r .value | tr -d '\n'`
      export AZURE_TENANT_ID=`az keyvault secret show --vault-name idjhomelabakv --name azure-payg-dnssp-client-tenantid -o json | jq -r .value | tr -d '\n'`
      export AZURE_DNS_ZONE_RESOURCE_GROUP="idjDNSrg"
      export AZURE_DNS_ZONE="tpk.life"

      kubectl create secret generic azuredns-config --from-literal=client-secret=$AZURE_CERT_MANAGER_SP_PASSWORD
    become: true
    args:
      chdir: /
      
  - name: Set Cluster Issuer
    ansible.builtin.shell: |
      # These should here. But I want which to fail if absent
      which jq
      which az

      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

      export AZURE_CERT_MANAGER_SP_APP_ID=`az keyvault secret show --vault-name idjhomelabakv --name azure-payg-dnssp-client-id -o json | jq -r .value | tr -d '\n'`
      export AZURE_SUBSCRIPTION_ID=`az keyvault secret show --vault-name idjhomelabakv --name azure-payg-dnssp-client-subid -o json | jq -r .value | tr -d '\n'`
      export AZURE_TENANT_ID=`az keyvault secret show --vault-name idjhomelabakv --name azure-payg-dnssp-client-tenantid -o json | jq -r .value | tr -d '\n'`
      export AZURE_DNS_ZONE_RESOURCE_GROUP="idjDNSrg"
      export AZURE_DNS_ZONE="tpk.life"

      cat <<EOF > certmanagerazure.yaml
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: azuredns-issuer
      spec:
        acme:
          email: isaac.johnson@gmail.com
          preferredChain: ""
          privateKeySecretRef:
            name: letsencrypt-azuredns-prod
          server: https://acme-v02.api.letsencrypt.org/directory
          solvers:
          - dns01:
              azureDNS:
                clientID: $AZURE_CERT_MANAGER_SP_APP_ID
                clientSecretSecretRef:
                # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
                  name: azuredns-config
                  key: client-secret
                subscriptionID: $AZURE_SUBSCRIPTION_ID
                tenantID: $AZURE_TENANT_ID
                resourceGroupName: $AZURE_DNS_ZONE_RESOURCE_GROUP
                hostedZoneName: $AZURE_DNS_ZONE
                # Azure Cloud Environment, default to AzurePublicCloud
                environment: AzurePublicCloud
            selector:
              dnsZones:
              - $AZURE_DNS_ZONE
      EOF

      kubectl apply -f certmanagerazure.yaml
    become: true
    args:
      chdir: /