- name: Backup K8s Setup
  hosts: all

  tasks:

  - name: create dir and test kubeconfig
    ansible.builtin.shell: |
      mkdir -p /tmp/k8sbackups
      chmod 644 /etc/rancher/k3s/k3s.yaml
      kubectl get nodes --kubeconfig=/etc/rancher/k3s/k3s.yaml
      # Backup Main Items
      kubectl get secrets --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_secrets.yaml 
      kubectl get services --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_services.yaml 
      kubectl get configmaps --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_configmaps.yaml 
      kubectl get deployments --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_deployments.yaml 
      kubectl get ingress --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_ingress.yaml 
      kubectl get endpoints --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_endpoints.yaml 
      kubectl get hpas --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_hpas.yaml 
      kubectl get pvcs --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_pvcs.yaml 
      kubectl get clusterissuers --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_clusterissuers.yaml 
      kubectl get issuers --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_issuers.yaml 
      kubectl get clusterroles --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_clusterroles.yaml 
      kubectl get clusterrolebindingss --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_clusterrolebindingss.yaml 
      kubectl get roles --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_roles.yaml 
      kubectl get rolebindingss --all-namespaces -o yaml --kubeconfig=/etc/rancher/k3s/k3s.yaml > {{ CLUSTERNAME }}_all_rolebindings.yaml 
     
      

  - name: create dir and test kubeconfig
    ansible.builtin.shell: |
      tar -czvf ./{{ CLUSTERNAME }}_$(date +%Y-%m-%d_%H-%M-%S)_backup.tgz 
      cp ./{{ CLUSTERNAME }}_$(date +%Y-%m-%d_%H-%M-%S)_backup.tgz {{ BACKUPMOUNT }}
    args:
      chdir: /tmp
