- name: Backup K8s Setup
  hosts: all

  tasks:
  - name: Transfer the script
    copy: src=backupK8s.sh dest=/tmp mode=0755

  - name: Create K8s backup
    command: sh /tmp/backupK8s.sh
    args:
      chdir: /tmp

  - name: transfer backup to NAS
    ansible.builtin.shell: |
      set -x
      ls -ltra | tail -n10
      cp ./backup_k8s.tgz {{ BACKUPMOUNT }}/{{ CLUSTERNAME }}_$(date +%Y-%m-%d_%H-%M-%S)_backup.tgz
    args:
      chdir: /tmp
