- name: Check for Broken Services
  hosts: all

  tasks:
  - name: Transfer the script
    copy: src=checkWebsiteAndPage.sh dest=/tmp mode=0755

  - name: Check Immich
    ansible.builtin.shell: |
      ./checkWebsiteAndPage.sh  {{ item }} {{ RESENDTOKEN }} {{ FROMEMAIL }} {{ TOEMAIL }}
    loop: "{{ hostlist.split(',') }}"
    args:
      chdir: /tmp
