- name: Check for Blog Posts
  hosts: all

  tasks:
  - name: Check For Dir
    stat:
      path: /tmp/jekyll
    register: register_ghco

  - name: Checkout Blog Repo if DNE
    command: git clone https://idjohnson:{{ GHTOKEN }}@github.com/idjohnson/jekyll-blog.git /tmp/jekyll
    when: not register_ghco.stat.exists

  - name: go to main and update
    ansible.builtin.shell: |
      cd /tmp/jekyll && git reset --hard && git checkout main && git pull

  - name: Transfer the script
    copy: src=findAndMergeBlogPosts.sh dest=/tmp mode=0755

  # use ACTION=dryrun or ACTION=DOIT
  - name: Install GH CLI
    ansible.builtin.shell: |
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      NONINTERACTIVE=1 brew install gh
    args:
      chdir: /tmp

  - name: Check for PRs
    ansible.builtin.shell: |
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      ./findAndMergeBlogPosts.sh /tmp/jekyll {{ GHTOKEN }}
    args:
      chdir: /tmp

