- name: Cleanup Backups
  hosts: all

  tasks:
  - name: Transfer the script
    copy: src=cleanupfolder.sh dest=/tmp mode=0755

  # use ACTION=dryrun or ACTION=DOIT
  - name: Run the script
    ansible.builtin.shell: |
      ./cleanupfolder.sh {{ FOLDER }} {{ NUMBACKUPS }} {{ ACTION}}
    args:
      chdir: /tmp