---
- name: Install Cloud Custodian
  hosts: all

  tasks:
  - name: Install Python3
    ansible.builtin.shell: |
      apt-get install -y python3 python3-venv python3-pip
    become: true
    args:
      chdir: /tmp

  - name: Check Version
    ansible.builtin.shell: |
      python3 -m pip --version
    args:
      chdir: /tmp

  - name: Install Custodian locally
    ansible.builtin.shell: |
      umask 0002
      python3 -m venv custodian
      source custodian/bin/activate
      pip install c7n  
    become: true
    args:
      chdir: /tmp

  - name: Pull Docker Image
    ansible.builtin.shell: |
      docker pull cloudcustodian/c7n  
    args:
      chdir: /tmp
