
- name: Install and Configure GlusterFS
  hosts: all

  tasks:
  - name: Set IPTables entry (if Firewall enabled)
    ansible.builtin.shell: |
      iptables -I INPUT -p all -s {{ item.name }} -j ACCEPT
    become: true
    ignore_errors: True
    loop: "{{ hosts }}"

  - name: Install glusterfs server
    ansible.builtin.shell: |
       apt update
       apt install -y glusterfs-server
    become: true

  - name: GlusterFS server - Start and check status
    ansible.builtin.shell: |
       service glusterd start
       sleep 5
       service glusterd status
    become: true


  - name: Create First Brick
    ansible.builtin.shell: |
       mkdir -p /mnt/glusterfs/brick1/gv0
    become: true

- name: Volume Create and Start on Primary
  hosts: AnnaMacbook

  tasks:
  - name: GlusterFS Peer Probe
    ansible.builtin.shell: |
       gluster peer probe {{ item.name }}
       gluster peer probe {{ item.name }}
       gluster peer probe {{ item.name }}
    become: true
    ignore_errors: True
    loop: "{{ hosts }}"

  - name: GlusterFS Peer Status
    ansible.builtin.shell: |
       gluster peer status
    become: true

  - name: Create GV0 Volume
    ansible.builtin.shell: |
       gluster volume create gv0 replica 3 {{ hosts[0].name }}:/mnt/glusterfs/brick1/gv0 {{ hosts[1].name }}:/mnt/glusterfs/brick1/gv0 {{ hosts[2].name }}:/mnt/glusterfs/brick1/gv0
    become: true

  - name: Start GV0 Volume
    ansible.builtin.shell: |
       gluster volume start gv0
       gluster volume info
    become: true

  - name: Check Status of Volume
    ansible.builtin.shell: |
       gluster volume info
    become: true