---
- name: Reload K3s
  hosts: all

  tasks:
  - name: Install Python3
    ansible.builtin.shell: |
      whoami
      pwd
    args:
      chdir: /tmp

  - name: Install Python3
    ansible.builtin.shell: |
      apt-get install -y python3 python3-venv python3-pip
    become: true
    args:
      chdir: /tmp

  - name: Install Cifs and iscsi
    ansible.builtin.shell: |
      apt-get install -y cifs-utils open-iscsi
    become: true
    args:
      chdir: /tmp

  - name: Install GCP Fuse
    ansible.builtin.shell: |
      export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
      rm -f /etc/apt/sources.list.d/gcsfuse.list || true
      echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      apt-get update
      apt-get install -y gcsfuse
    become: true
    args:
      chdir: /tmp

  - name: Add AWS CLI
    ansible.builtin.shell: |
      apt-get install -y awscli s3fs
    become: true
    args:
      chdir: /tmp

- name: Update Primary
  hosts: AnnaMacbook

  tasks:
  - name: Test host
    ansible.builtin.shell: |
      cat /var/lib/rancher/k3s/server/node-token | tr -d '\n'
    register: nodetokenresult
    become: true
    args:
      chdir: /tmp

  - name: Set Global Var
    setglobal: name=myglobaltoken value="{{nodetokenresult}}"
      

      
- name: Update Workers
  hosts: builder-MacBookPro2:isaac-MacBookPro

  tasks:
  - name: Test host
    ansible.builtin.shell: |
      pwd
      ifconfig | grep 192
      echo "TEST1"
      echo {{ hostvars['AnnaMacbook']['nodetokenresult'] }}
      echo "TEST2"
      echo {{ myglobaltoken }}